### PR TITLE
Validation for verifyIfAllLinksActive()

### PR DESCRIPTION
**Pull request by shashiranjan99**

### CODE REVIEW

**Review by maha99tests — COMMENTED** [review]
How does this work? I don't see any statement that returns true or false

**Comment by shashiranjan99** [comment]
I have added an assert which will check if the link is giving 200 response or not. If the response is other than 200 it will simply break and test case will fail.

**Comment by maha99tests** [comment]
Its inside the try catch block, so the function will return silently without raising any exceptions

**Comment by shashiranjan99** [comment]
It will return the last link which is not valid with the response

**Comment by shashiranjan99** [comment]
Should in remove the try catch

**Review by maha99tests — APPROVED** [review]

**Pull request merged**
